*Accompanying code examples of the book "Introduction to Artificial Neural Networks and Deep Learning: A Practical Guide with Applications in Python" by [Sebastian Raschka](https://sebastianraschka.com). All code examples are released under the [MIT license](https://github.com/rasbt/deep-learning-book/blob/master/LICENSE). If you find this content useful, please consider supporting the work by buying a [copy of the book](https://leanpub.com/ann-and-deeplearning).*

Other code examples and content are available on [GitHub](https://github.com/rasbt/deep-learning-book). The PDF and ebook versions of the book are available through [Leanpub](https://leanpub.com/ann-and-deeplearning).

# Appendix G - TensorFlow Basics

* [TensorFlow in a Nutshell](#TensorFlow-in-a-Nutshell)
* [Installation](#Installation)
* [Computation Graphs](#Computation-Graphs)
* [Variables](#Variables)
* [Placeholder Variables](#Placeholder-Variables)

* [CPU and GPU](#CPU-and-GPU)

In [1]:
%load_ext watermark
%watermark -a 'Sebastian Raschka' -d -p tensorflow,numpy

Sebastian Raschka 2017-03-27 

tensorflow 1.0.1
numpy 1.12.1


## TensorFlow in a Nutshell

## Installation

## Computation Graphs

In [2]:
import tensorflow as tf

g = tf.Graph()

with g.as_default() as g:
    tf_x = tf.constant([[1., 2.], 
                        [3., 4.],
                        [5., 6.]], dtype=tf.float32)
    col_sum = tf.reduce_sum(tf_x, axis=0)

print('tf_x:\n', tf_x)
print('\ncol_sum:\n', col_sum)

tf_x:
 Tensor("Const:0", shape=(3, 2), dtype=float32)

col_sum:
 Tensor("Sum:0", shape=(2,), dtype=float32)


In [3]:
with tf.Session(graph=g) as sess:
    mat, csum = sess.run([tf_x, col_sum])
    
print('mat:\n', mat)
print('\ncsum:\n', csum)

mat:
 [[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]]

csum:
 [  9.  12.]


In [4]:
g = tf.Graph()

with g.as_default() as g:
    tf_x = tf.constant([[1., 2.], 
                        [3., 4.],
                        [5., 6.]], dtype=tf.float32)
    col_sum = tf.reduce_sum(tf_x, axis=0)
    col_sum_times_2 = col_sum * 2


with tf.Session(graph=g) as sess:
    csum_2 = sess.run(col_sum_times_2)
    
print('csum_2:\n', csum_2)

csum_2:
 [ 18.  24.]


## Variables

In [5]:
g = tf.Graph()

with g.as_default() as g:
    tf_x = tf.Variable([[1., 2.], 
                        [3., 4.],
                        [5., 6.]], dtype=tf.float32)
    x = tf.constant(1., dtype=tf.float32)
    
    # add a constant to the matrix:
    tf_x = tf_x + x
    
with tf.Session(graph=g) as sess:
    sess.run(tf.global_variables_initializer())
    result = sess.run(tf_x)
    
print(result)

[[ 2.  3.]
 [ 4.  5.]
 [ 6.  7.]]


In [6]:
with tf.Session(graph=g) as sess:
    sess.run(tf.global_variables_initializer())
    result = sess.run(tf_x)
    result = sess.run(tf_x)

print(result)

[[ 2.  3.]
 [ 4.  5.]
 [ 6.  7.]]


In [7]:
g = tf.Graph()

with g.as_default() as g:
    tf_x = tf.Variable([[1., 2.], 
                        [3., 4.],
                        [5., 6.]], dtype=tf.float32)
    x = tf.constant(1., dtype=tf.float32)
    
    update_tf_x = tf.assign(tf_x, tf_x + x)


with tf.Session(graph=g) as sess:
    sess.run(tf.global_variables_initializer())
    result = sess.run(update_tf_x)
    result = sess.run(update_tf_x)

print(result)

[[ 3.  4.]
 [ 5.  6.]
 [ 7.  8.]]


## Placeholder Variables

In [8]:
import numpy as np

g = tf.Graph()

with g.as_default() as g:
    tf_x = tf.placeholder(dtype=tf.float32,
                          shape=(3, 2))

    output = tf.matmul(tf_x, tf.transpose(tf_x))


with tf.Session(graph=g) as sess:
    sess.run(tf.global_variables_initializer())
    np_ary = np.array([[3., 4.],
                          [5., 6.],
                          [7., 8.]])
    feed_dict = {tf_x: np_ary}
    print(sess.run(output,
                   feed_dict=feed_dict))

[[  25.   39.   53.]
 [  39.   61.   83.]
 [  53.   83.  113.]]


## Saving and Loading Variables

In [9]:
g = tf.Graph()

with g.as_default() as g:
    
    tf_x = tf.Variable([[1., 2.], 
                        [3., 4.],
                        [5., 6.]], dtype=tf.float32)
    x = tf.constant(1., dtype=tf.float32)
    
    update_tf_x = tf.assign(tf_x, tf_x + x)
    
    # initialize a Saver, which gets all variables
    # within this computation graph context
    saver = tf.train.Saver()

with tf.Session(graph=g) as sess:
    sess.run(tf.global_variables_initializer())
    result = sess.run(update_tf_x)
    
    saver.save(sess, save_path='./my-model.ckpt')

In [10]:
g = tf.Graph()

with g.as_default() as g:
    
    tf_x = tf.Variable([[1., 2.], 
                        [3., 4.],
                        [5., 6.]], dtype=tf.float32)
    x = tf.constant(1., dtype=tf.float32)
    
    update_tf_x = tf.assign(tf_x, tf_x + x)
    
    # initialize a Saver, which gets all variables
    # within this computation graph context
    saver = tf.train.Saver()

with tf.Session(graph=g) as sess:
    sess.run(tf.global_variables_initializer())
    
    for epoch in range(100):
        result = sess.run(update_tf_x)
        if not epoch % 10:
            saver.save(sess, 
                       save_path='./my-model-multiple_ckpts.ckpt', 
                       global_step=epoch)
    

In [11]:
g = tf.Graph()

with g.as_default() as g:
    
    tf_x = tf.Variable([[1., 2.], 
                        [3., 4.],
                        [5., 6.]], dtype=tf.float32)
    x = tf.constant(1., dtype=tf.float32)
    
    update_tf_x = tf.assign(tf_x, tf_x + x)
    
    # initialize a Saver, which gets all variables
    # within this computation graph context
    saver = tf.train.Saver()

with tf.Session(graph=g) as sess:
    saver.restore(sess, save_path='./my-model.ckpt')
    result = sess.run(update_tf_x)
    print(result)

[[ 3.  4.]
 [ 5.  6.]
 [ 7.  8.]]


In [12]:
with tf.Session(graph=g) as sess:
    saver.restore(sess, save_path='./my-model-multiple_ckpts.ckpt-90')
    result = sess.run(update_tf_x)
    print(result)

[[ 93.  94.]
 [ 95.  96.]
 [ 97.  98.]]


- You'll notice you still need to create the weights and bias Tensors in Python. The tf.train.Saver.restore() function loads the saved data into weights and bias.

- Since tf.train.Saver.restore() sets all the TensorFlow Variables, you don't need to call tf.global_variables_initializer().

## Naming TensorFlow Objects

In [13]:
g = tf.Graph()

with g.as_default() as g:
    
    tf_x = tf.Variable([[1., 2.], 
                        [3., 4.],
                        [5., 6.]], dtype=tf.float32)
    
    tf_y = tf.Variable([[7., 8.], 
                        [9., 10.],
                        [11., 12.]], dtype=tf.float32)
    
    x = tf.constant(1., dtype=tf.float32)
    update_tf_x = tf.assign(tf_x, tf_x + x)
    saver = tf.train.Saver()

with tf.Session(graph=g) as sess:
    sess.run(tf.global_variables_initializer())
    result = sess.run(update_tf_x)
    
    saver.save(sess, save_path='./my-model.ckpt')

In [14]:
g = tf.Graph()

with g.as_default() as g:
    
    tf_y = tf.Variable([[7., 8.], 
                        [9., 10.],
                        [11., 12.]], dtype=tf.float32)
    
    tf_x = tf.Variable([[1., 2.], 
                        [3., 4.],
                        [5., 6.]], dtype=tf.float32)
    
    x = tf.constant(1., dtype=tf.float32)
    update_tf_x = tf.assign(tf_x, tf_x + x)
    saver = tf.train.Saver()
    
with tf.Session(graph=g) as sess:
    saver.restore(sess, save_path='./my-model.ckpt')
    result = sess.run(update_tf_x)
    print(result)

[[  8.   9.]
 [ 10.  11.]
 [ 12.  13.]]


In [15]:
import tensorflow as tf

g = tf.Graph()

with g.as_default() as g:
    
    tf_x = tf.Variable([[1., 2.], 
                        [3., 4.],
                        [5., 6.]], 
                       name='tf_x_0',
                       dtype=tf.float32)
    
    tf_y = tf.Variable([[7., 8.], 
                        [9., 10.,
                         ]], 
                       name='tf_y_0',
                       dtype=tf.float32)
    
    x = tf.constant(1., dtype=tf.float32)
    update_tf_x = tf.assign(tf_x, tf_x + x)
    saver = tf.train.Saver()

with tf.Session(graph=g) as sess:
    sess.run(tf.global_variables_initializer())
    result = sess.run(update_tf_x)
    
    saver.save(sess, save_path='./my-model.ckpt')

In [16]:
g = tf.Graph()

with g.as_default() as g:
    
    tf_y = tf.Variable([[7., 8.], 
                        [9., 10.,
                         ]], 
                       name='tf_y_0',
                       dtype=tf.float32)
    
    tf_x = tf.Variable([[1., 2.], 
                        [3., 4.],
                        [5., 6.]], 
                       name='tf_x_0',
                       dtype=tf.float32)
    
    x = tf.constant(1., dtype=tf.float32)
    update_tf_x = tf.assign(tf_x, tf_x + x)
    saver = tf.train.Saver()
    
with tf.Session(graph=g) as sess:
    saver.restore(sess, save_path='./my-model.ckpt')
    result = sess.run(update_tf_x)
    print(result)

[[ 3.  4.]
 [ 5.  6.]
 [ 7.  8.]]


## CPU and GPU

```python
with tf.Session() as sess:
    with tf.device("/gpu:1"):




from tensorflow.python.client import device_lib

device_lib.list_local_devices()
```

## TensorBoard

In [17]:
# Simple graph visualization

g = tf.Graph()

with g.as_default() as g:
    

    tf_x = tf.Variable([[1., 2.], 
                        [3., 4.],
                        [5., 6.]], 
                       name='tf_x_0',
                       dtype=tf.float32)
    
    tf_y = tf.Variable([[7., 8.], 
                        [9., 10.],
                        [11., 12.]], 
                       name='tf_y_0',
                       dtype=tf.float32)

    output = tf_x + tf_y
    output = tf.matmul(tf.transpose(tf_x), output)

In [18]:
with tf.Session(graph=g) as sess:
    sess.run(tf.global_variables_initializer())
    
    # create FileWrite object that writes the logs
    file_writer = tf.summary.FileWriter(logdir='logs/1', graph=g)
    result = sess.run(output)
    print(result)

[[ 124.  142.]
 [ 160.  184.]]


    Desktop Sebastian$ tensorboard --logdir logs/1
    Starting TensorBoard b'41' on port 6006
    (You can navigate to http://xxx.xxx.x.xx:6006)

![](images/tensorboard-1.png)

In [19]:
# Graph visualization with name scopes

g = tf.Graph()

with g.as_default() as g:
    
    tf_x = tf.Variable([[1., 2.], 
                        [3., 4.],
                        [5., 6.]], 
                       name='tf_x_0',
                       dtype=tf.float32)
    
    tf_y = tf.Variable([[7., 8.], 
                        [9., 10.],
                        [11., 12.]], 
                       name='tf_y_0',
                       dtype=tf.float32)
    
    # add custom name scope
    with tf.name_scope('addition'):
        output = tf_x + tf_y
        
    # add custom name scope
    with tf.name_scope('matrix_multiplication'):
        output = tf.matmul(tf.transpose(tf_x), output)
    
with tf.Session(graph=g) as sess:
    sess.run(tf.global_variables_initializer())
    file_writer = tf.summary.FileWriter(logdir='logs/2', graph=g)
    result = sess.run(output)
    print(result)

[[ 124.  142.]
 [ 160.  184.]]


    Desktop Sebastian$ tensorboard --logdir logs/2
    Starting TensorBoard b'41' on port 6006
    (You can navigate to http://xxx.xxx.x.xx:6006)

![](images/tensorboard-2.png)
![](images/tensorboard-3.png)

In [20]:
# Graph visualization and variable inspection

g = tf.Graph()

with g.as_default() as g:

    some_value = tf.placeholder(dtype=tf.int32, 
                                shape=None, 
                                name='some_value')
    
    tf_x = tf.Variable([[1., 2.], 
                        [3., 4.],
                        [5., 6.]], 
                       name='tf_x_0',
                       dtype=tf.float32)
    
    tf_y = tf.Variable([[7., 8.], 
                        [9., 10.],
                        [11., 12.]], 
                       name='tf_y_0',
                       dtype=tf.float32)
    
    with tf.name_scope('addition'):    
        output = tf_x + tf_y
        
    with tf.name_scope('matrix_multiplication'):
        output = tf.matmul(tf.transpose(tf_x), output)
    
    with tf.name_scope('update_tensor_x'):  
        tf_const = tf.constant(2., shape=None, name='some_const')
        update_tf_x = tf.assign(tf_x, tf_x * tf_const)
    
    # create summaries
    tf.summary.scalar(name='some_value', tensor=some_value)    
    tf.summary.histogram(name='tf_x_values', values=tf_x)  

    # merge all summaries into a single operation
    merged_summary = tf.summary.merge_all()

In [ ]:
with tf.Session(graph=g) as sess:
    
    sess.run(tf.global_variables_initializer())
    
    # create FileWrite object that writes the logs
    file_writer = tf.summary.FileWriter(logdir='logs/3', graph=g)
    
    for i in range(5):
        # fetch the summary from the graph
        result, summary = sess.run([update_tf_x, merged_summary],
                                    feed_dict={some_value: i})
        # write the summary to the log
        file_writer.add_summary(summary=summary, global_step=i)
        file_writer.flush()

    Desktop Sebastian$ tensorboard --logdir logs/3
    Starting TensorBoard b'41' on port 6006
    (You can navigate to http://xxx.xxx.x.xx:6006)

![](images/tensorboard-4.png)

![](images/tensorboard-5.png)

![](images/tensorboard-6.png)